---
- name: Send an email using community.general.mail
  hosts: localhost
  become: false
  tasks:
    - name: Send an email using community.general.mail
      ansible.builtin.mail:
        from: 2020it0875@svce.ac.in
        to:
          - srigopinath.angamuthuraja@movate.com
        subject: "Test Email from AWX"
        body: "This is a test email sent from AWX without using mailx."
        host: 'smtp.google.com'
        port: 587
        username: 2020it0875@svce.ac.in
        password: #Gopinaths2830
        secure: starttls
