---
- name: Send email via AWX
  hosts: localhost
  tasks:
    - name: Send mail
      community.general.mail:
        host: smtp.gmail.com
        port: 587
        username: 2020it0875@svce.ac.in
        password: #Gopinaths2830
        from: 2020it0875@svce.ac.in
        to: vangalshravankumar.srinivaschary@movate.com
        subject: to test awx
        body: hii it is pinging
      delegate_to: localhost
