---
- name: To install mail x
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: install sudo
      apt:
        name: sudo
        state: present
      when: ansible_os_family == 'Debian'
    - name: to install mailx
      apt:
        name: bsd-mailx
        state: present
      when: ansible_os_family == 'Debian'

