---
- name: Ensure sudo is installed and install mailx
  hosts: localhost
  become: yes
  become_method: su
  tasks:
    - name: sudo
      apt:
        name: sudo
        state: present
      when: ansible_os_family == "Debian"
    - name: install mailx
      apt:
        name: bsd-mailx
        state: present
      when: ansible_os_family == "Debian"
