---
- name: To install mail x
  hosts: localhost
  become: yes
  tasks:

    - name: to install mailx
      apt:
        name: bsd-mailx
        state: present
      when: ansible_os_family == 'Debian'
