---
- name: Ensure sudo is installed and install mailx
  hosts: localhost
  become: yes
  tasks:
    - name: sudo
      ansible.builtin.apt:
        name: sudo
        state: present
      when: ansible_os_family == "Debian"
    - name: install mailx
      ansible.builtin.apt:
        name: bsd-mailx
        state: present
      when: ansible_os_family == "Debian"
