---
- name: the mail have to send 
  hosts: localhost
  become: yes
  tasks:
    - name: Script call
      ansible.builtin.command:
        cmd: python3 Sendmain.py
      args:
        chdir: /home/azureuser
